---
apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-operator
data:
  global: ""
  sysctlTuner: |
    params:
     vm.swappiness: "0"
     kernel.num_balancing: "0"
     net.core.netdev_max_backlog: "5000"
     net.core.rmem_max: "16777216"
     net.core.wmem_max: "16777216"
    sleep: "300"